name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        $CONDA/bin/flake8 .
    - name: Lint with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .

